name: Deploy StandBlog Laravel Application to Production Server

on: 
    push:
        branches: 
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with: 
                php-version: 8.2

            - name: Install Composer Dependencies
              run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

               
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'

            - name: Install NPM Dependencies
              run: npm ci 

            - name: Install NPM Assets
              run: npm run build

            - name: Synchronize Files To Server
              uses: easingthemes/ssh-deploy@main
              env: 
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                SOURCE: "."
                REMOTE_HOST: ${{ secrets.VPS_HOST }}
                REMOTE_USER: ${{ secrets.VPS_USER }}
                TARGET: "/var/www/adminsolarecom.minthantoo.com"

            - name: Run Remote/Artisan Commands
              uses: appleboy/ssh-action@v0.1.6
              with:
                host: ${{ secrets.VPS_HOST }} 
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  cd /var/www/adminsolarecom.minthantoo.com
                  git pull origin main
                  # Install any new dependencies
                  composer install --no-dev --prefer-dist
                  php artisan migrate --force
                  php artisan optimize
